### ISSUE TITLE
How Can I Use THis?

### ISSUE THREAD

**Issue by pialechini** [warlockbrawl/war3observer#12]
Hi.Special thanks with your work.
I don't undrestand how can I use this app.
Can you explain a little better?

**Comment by sides** [comment]
Did you follow these steps? https://github.com/sides/war3observer#usage

Can you be more specific to what issue you're facing?

**Comment by pialechini** [comment]
Yes I did. But in patch 1.26a & dota Allstars map it did not work for me.
Can you explain how this app fetchs game data?

**Comment by sides** [comment]
This uses the observer API which was added to the game in patch 1.30.2 or around that, so it will not work on any versions before that.
