### ISSUE TITLE
Invalid Connection header: ['keep-alive'] With custome port and ip 

### ISSUE THREAD

**Issue by grossmaul2130** [warlockbrawl/war3observer#7]
war3observer.exe started with --port and --host when trying to connect to the set ip and port 
Invalid Connection header: ['keep-alive'] is returned. Handshake fails after first request to the socket. Attached the headers from firefox. As you can see websocket is instantly closing the connection. 
![handshake](https://user-images.githubusercontent.com/55811924/65636442-92341300-dfe2-11e9-9b3a-c970185da947.PNG)

**Comment by sides** [comment]
Hi, are you making a http request to the server? That will not give you any results. Have you tried making a websocket connection to it?

**Comment by grossmaul2130** [comment]
Indeed you are correct. I tryed to connect via http. I can reach the websocket on my choosen adress. But how can i transalte this to overlay output?

**Comment by grossmaul2130** [comment]
Case can be closed i needed to changene the ip and port in the .js file to my custom choosen websocket as well and host my 1v1-overview.html on a small webserver. Your hint with the websocket was very helpfull. Thank you a lot

**Comment by sides** [comment]
@grossmaul2130 Glad you figured it out. For the record you shouldn't have to edit js files in the client. This may be relevant to you: https://github.com/warlockbrawl/war3observer/issues/4#issuecomment-522701958
