### ISSUE TITLE
Error when playing, "Attempted to find 2 players but found only 0"

### ISSUE THREAD

**Issue by Deepfire1987** [warlockbrawl/war3observer#9]
Hello,

i've tried it several times to fix, but i can't it on my own.

war3observer.exe is saying:

Traceback (most recent calls last):
   File "war3observer\server.py", line 45, in send_state_to_client
   File "war3observer\game.py", line 140, in update
   File "war3observer\game.py", line 112, in _find_players
Exception: Attempted to find 2 players but found only 0

Please help me to fix it, i'd like to stream with it :)

Best regards,
Deepfire

**Comment by sides** [comment]
Hello, sorry for this super late response.

Are you observing a game or playing in it? Just to be sure, this tool is only for observing games (casting).

**Comment by Deepfire1987** [comment]
Hi, Oh damn, i was playing. Is there a similar Tool for players. Thanks for answering. Deepfire -------- Ursprüngliche Nachricht --------Betreff: Re: [warlockbrawl/war3observer] Error: An error occured while updating the game state (#9)Von: sides An: warlockbrawl/war3observer Cc: Deepfire1987 ,Author Hello, sorry for this super late response.
Are you observing a game or playing in it? Just to be sure, this tool is only for observing games (casting).

**Comment by JFGHT** [comment]
@Deepfire1987 No.

1.- You could be cheating.
2.- This is the Observer API, made by Blizzard to ease the build of better GUIs for observing streams.

There is this:
https://github.com/dethredic/WC3StreamerOverlay

Which is different.

**Comment by Deepfire1987** [comment]
oh thanks, but I have this one already. This is only for the Player Stats and Race. I want the overlay for the hero skills and upgrades.

**Comment by JFGHT** [comment]
For that you need to build it yourself since it needs reverse engineering (and it's illegal).

**Comment by Deepfire1987** [comment]
Hi again,
thanks for your advice. So I won't try it. 
Actually I am searching for a script which can show the map name ingame.
Do you know this?

Best wishes 
Deepfire

**Comment by sides** [comment]
@Deepfire1987 just for full clarity, the author of grubby's stats tool released it public a while ago, which I think is what you were originally looking for here: https://www.reddit.com/r/WC3/comments/df1s7k/well_known_streamer_overlay_now_available_for/

Like JFGHT said it's quite iffy the way it's done and I don't really condone it but a lot of streamers use it already.

I think this tool shows the map name as well.
